### ISSUE TITLE
Unable to delete docker from UBUNTU 16.04 LTS

### ISSUE THREAD

**Issue by shashidharshridhar** [BradleyA/docker-scripts#12]
Hi,
      I ran 
$ ./setup-dockerd.sh 

./setup-dockerd.sh 49 [INFO]:	Changes made to
	/etc/docker/dockerd-configuration-file will be added to Upstart and
	Systemd configuration files for dockerd.

./setup-dockerd.sh 76 [INFO]:	Update files for dockerd (Upstart and SysVinit
	configuration file) for Ubuntu 14.04.
./setup-dockerd.sh 89 [INFO]:	Copy /etc/docker/docker.org to
	/etc/docker/docker without Custom_dockerd_Configuration_File section.
./setup-dockerd.sh 92 [INFO]:	Append /etc/docker/dockerd-configuration-file
	onto /etc/docker/docker.
./setup-dockerd.sh 95 [INFO]:	Move /etc/docker/docker to /etc/default/docker
./setup-dockerd.sh 98 [INFO]:	dockerd (Upstart and SysVinit configuration
	file) for Ubuntu 14.04 has been updated.

./setup-dockerd.sh 99 [INFO]:	If you are using upstart, Run
	'sudo service docker restart' for dockerd to read /etc/default/docker.

./setup-dockerd.sh 106 [INFO]:	Update files for dockerd (systemd configuration
	file) on Ubuntu 16.04.
/etc/docker/start-dockerd-with-systemd.sh 113 [INFO]:	Creating
	/etc/docker/10-override.conf file.
/etc/docker/start-dockerd-with-systemd.sh 121 [INFO]:	10-override.conf move
	to /etc/systemd/system/docker.service.d.
/etc/docker/start-dockerd-with-systemd.sh 127 [INFO]:	Done

./setup-dockerd.sh 116 [INFO]:	If you are using systemd, Run
	'sudo systemctl enable dockerd-configuration-file.service'
	to start on boot.
./setup-dockerd.sh 117 [INFO]:	Run 'sudo systemctl enable docker'
	to start on boot.
./setup-dockerd.sh 118 [INFO]:	Run 'sudo systemctl restart docker'

After that I tried removing the docker but it is throwing an error telling 

$ sudo apt-get remove docker*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker-scripts

Can you please let me know how can I resolve it. I want to remove the scripts and docker completely so that I can re install everything. Please help.

Thanks,
Shashi

**Comment by shashidharshridhar** [comment]
Unable to restart docker and this issue occurred after I ran the script. 
$ systemctl restart docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

**Comment by BradleyA** [comment]
I'm closing this issue, because I have not heard back from about the solution offered.  If this solution did not fix your incident, please feel free to reopen this issue or open a new issue.
